[FLOWS_1495] - Update Survey component.
weni-ai/weni-integrations-webapp pull request #392
Opened 2024-05-02 14:21 UTC by acnormun

## Description
### Type of Change>
* * [ ] Bugfix
* * [ ] Feature
* * [ ] Code style update (formatting, local variables)
* * [x] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other

### Motivation and Context
Upgrade vue version.

### Summary of Changes
Change store from vuex to pinia.

2024-05-03 18:36 UTC, paulobernardoaf requested changes

2024-05-03 18:36 UTC, paulobernardoaf commented on src/components/Survey/index.vue
> +        // unnnicCallAlert({
Remove unused code

2024-05-03 18:36 UTC, paulobernardoaf commented on src/components/Survey/index.vue
> +  // import unnnicCallAlert from '@weni/unnnic-system';
Remove unused code

2024-05-03 18:38 UTC, Aldemylla commented on src/components/Survey/index.vue
Remove commented dead code from this file

2024-05-07 20:56 UTC, Aldemylla approved these changes

2024-05-07 21:13 UTC, paulobernardoaf approved these changes

2024-05-07 21:15 UTC, merged