[RS-182] - Add store tests.
weni-ai/weni-integrations-webapp pull request #447
Opened 2024-10-02 17:31 UTC by acnormun

## Description
### Type of Change

* * [ ] Bugfix
* * [ ] Feature
* * [ ] Code style update (formatting, local variables)
* * [ ] Refactoring (no functional changes, no api changes)
* * [x] Tests
* * [ ] Other

### Motivation and Context
Add store tests.

### Summary of Changes
Added store tests.

2024-10-09 12:48 UTC, Aldemylla commented on src/tests/store/modules/appType/channels/generic.spec.js
> +    vi.clearAllMocks(); // Limpa todos os mocks antes de cada teste
Remove this comment or translate to english

2024-10-09 13:06 UTC, Aldemylla requested changes

2024-10-09 13:06 UTC, Aldemylla commented on src/tests/store/modules/appType/channels/whatsapp.spec.js
Remove repeated comments at this file, the code already sufficiently explains the functionality

2024-10-10 11:24 UTC, Aldemylla approved these changes

2024-10-10 14:22 UTC, cristiantela approved these changes

2024-10-18 12:41 UTC, merged